version: '3.5'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - conf/development
      - conf/development.secret
    ports:
      - 4000:4000
      - 9229:9229
    depends_on:
      - mysql
    volumes:
      - "./bin:/app/bin"
      - "./conf:/app/conf"
      - "./src:/app/src"
  mysql:
    image: mysql:5.7
    container_name: koa_sql
    env_file:
      - conf/development
      - conf/development.secret
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:

